In [1]:
import pandas as pd

#movies = pd.read_csv(r'C:\Users\Admin\Downloads\archive\movie.csv')

In [3]:
movies = pd.read_csv(r"C:\Users\gbrah\Downloads\Projects\archive\movie.csv")

In [4]:
movies.shape

(27278, 3)

In [5]:
movies.head(1)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

#ratings = pd.read_csv(r'C:\Users\Admin\Downloads\archive\rating.csv')

In [7]:
ratings = pd.read_csv(r"C:\Users\gbrah\Downloads\Projects\archive\rating.csv")

In [9]:
ratings.shape

(20000263, 4)

#tags = pd.read_csv(r'C:\Users\Admin\Downloads\archive\tag.csv')

In [10]:
tags = pd.read_csv(r"C:\Users\gbrah\Downloads\Projects\archive\tag.csv")

In [11]:
tags.shape

(465564, 4)

In [12]:
print(movies.shape)
print(ratings.shape)
print(tags.shape)

(27278, 3)
(20000263, 4)
(465564, 4)

In [13]:
print(movies.columns)
print(ratings.columns)
print(tags.columns)

Index(['movieId', 'title', 'genres'], dtype='object')
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [14]:
del ratings['timestamp']
del tags['timestamp']

In [15]:
print(movies.columns)
print(ratings.columns)
print(tags.columns)

Index(['movieId', 'title', 'genres'], dtype='object')
Index(['userId', 'movieId', 'rating'], dtype='object')
Index(['userId', 'movieId', 'tag'], dtype='object')

In [16]:
tags.head()

   userId  movieId            tag
0      18     4141    Mark Waters
1      65      208      dark hero
2      65      353      dark hero
3      65      521  noir thriller
4      65      592      dark hero

In [17]:
tags.iloc[1]

userId            65
movieId          208
tag        dark hero
Name: 1, dtype: object