In [7]:
import pandas as pd

In [8]:
pd.__version__

'2.3.3'

In [10]:
store=pd.read_csv(r"C:\Users\gbrah\Downloads\archive (1)\Sample Superstore Orders.csv")

In [11]:
store

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.00,41.9136,2,261.9600
1,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Chairs,2021,3,0.00,219.5820,3,731.9400
2,Office Supplies,Los Angeles,United States,Darrin Van Huff,6/12/2021,CA-2021-138688,90036.0,West,Corporate,6/16/2021,Second Class,California,Labels,2021,4,0.00,6.8714,2,14.6200
3,Furniture,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Tables,2020,7,0.45,-383.0310,5,957.5775
4,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Storage,2020,7,0.20,2.5164,2,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Technology,Los Angeles,United States,Ben Ferrer,12/24/2019,US-2019-138247,90045.0,West,Home Office,12/29/2019,Standard Class,California,Phones,2019,5,0.20,17.3656,7,173.6560
9990,Technology,Los Angeles,United States,Ben Ferrer,7/12/2019,CA-2019-110184,90036.0,West,Home Office,7/16/2019,Standard Class,California,Phones,2019,4,0.20,28.7928,8,255.9360
9991,Technology,Santa Barbara,United States,Maria Etezadi,6/6/2021,CA-2021-160717,93101.0,West,Home Office,6/11/2021,Standard Class,California,Phones,2021,5,0.20,226.7946,9,3023.9280
9992,Technology,Yuma,United States,Gary Hansen,10/16/2022,CA-2022-159282,85364.0,West,Home Office,10/21/2022,Standard Class,Arizona,Machines,2022,5,0.70,-479.9880,5,599.9850
9993,Technology,Louisville,United States,Sharelle Roach,4/17/2022,CA-2022-134845,80027.0,West,Home Office,4/23/2022,Standard Class,Colorado,Machines,2022,6,0.70,-3399.9800,5,2549.9850

In [12]:
id(store)

2442633731344

In [13]:
len(store)

9994

In [14]:
store.shape

(9994, 19)

In [15]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Order Date',
       'Order ID', 'Postal Code', 'Region', 'Segment', 'Ship Date',
       'Ship Mode', 'State', 'Sub-Category', 'Year Label', 'Days to Ship',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [16]:
len(store.columns)

19

In [17]:
store.isnull()

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
store.isnull().sum()

Category           0
City               0
Country/Region     0
Customer Name      0
Order Date         0
Order ID           0
Postal Code       11
Region             0
Segment            0
Ship Date          0
Ship Mode          0
State              0
Sub-Category       0
Year Label         0
Days to Ship       0
Discount           0
Profit             0
Quantity           0
Sales              0
dtype: int64

In [19]:
store[:]

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.00,41.9136,2,261.9600
1,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Chairs,2021,3,0.00,219.5820,3,731.9400
2,Office Supplies,Los Angeles,United States,Darrin Van Huff,6/12/2021,CA-2021-138688,90036.0,West,Corporate,6/16/2021,Second Class,California,Labels,2021,4,0.00,6.8714,2,14.6200
3,Furniture,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Tables,2020,7,0.45,-383.0310,5,957.5775
4,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Storage,2020,7,0.20,2.5164,2,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Technology,Los Angeles,United States,Ben Ferrer,12/24/2019,US-2019-138247,90045.0,West,Home Office,12/29/2019,Standard Class,California,Phones,2019,5,0.20,17.3656,7,173.6560
9990,Technology,Los Angeles,United States,Ben Ferrer,7/12/2019,CA-2019-110184,90036.0,West,Home Office,7/16/2019,Standard Class,California,Phones,2019,4,0.20,28.7928,8,255.9360
9991,Technology,Santa Barbara,United States,Maria Etezadi,6/6/2021,CA-2021-160717,93101.0,West,Home Office,6/11/2021,Standard Class,California,Phones,2021,5,0.20,226.7946,9,3023.9280
9992,Technology,Yuma,United States,Gary Hansen,10/16/2022,CA-2022-159282,85364.0,West,Home Office,10/21/2022,Standard Class,Arizona,Machines,2022,5,0.70,-479.9880,5,599.9850
9993,Technology,Louisville,United States,Sharelle Roach,4/17/2022,CA-2022-134845,80027.0,West,Home Office,4/23/2022,Standard Class,Colorado,Machines,2022,6,0.70,-3399.9800,5,2549.9850

In [20]:
store[0:10]

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.00,41.9136,2,261.9600
1,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Chairs,2021,3,0.00,219.5820,3,731.9400
2,Office Supplies,Los Angeles,United States,Darrin Van Huff,6/12/2021,CA-2021-138688,90036.0,West,Corporate,6/16/2021,Second Class,California,Labels,2021,4,0.00,6.8714,2,14.6200
3,Furniture,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Tables,2020,7,0.45,-383.0310,5,957.5775
4,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Storage,2020,7,0.20,2.5164,2,22.3680
5,Furniture,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Furnishings,2019,5,0.00,14.1694,7,48.8600
6,Office Supplies,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Art,2019,5,0.00,1.9656,4,7.2800
7,Technology,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Phones,2019,5,0.20,90.7152,6,907.1520
8,Office Supplies,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Binders,2019,5,0.20,5.7825,3,18.5040
9,Office Supplies,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Appliances,2019,5,0.00,34.4700,5,114.9000

In [21]:
store[0:20:5]

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.0,41.9136,2,261.960
5,Furniture,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Furnishings,2019,5,0.0,14.1694,7,48.860
10,Furniture,Los Angeles,United States,Brosina Hoffman,6/9/2019,CA-2019-115812,90032.0,West,Consumer,6/14/2019,Standard Class,California,Tables,2019,5,0.2,85.3092,9,1706.184
15,Office Supplies,Fort Worth,United States,Harold Pawlan,11/22/2020,US-2020-118983,76106.0,Central,Home Office,11/26/2020,Standard Class,Texas,Binders,2020,4,0.8,-3.8160,3,2.544

In [22]:
store.head()

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.00,41.9136,2,261.9600
1,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Chairs,2021,3,0.00,219.5820,3,731.9400
2,Office Supplies,Los Angeles,United States,Darrin Van Huff,6/12/2021,CA-2021-138688,90036.0,West,Corporate,6/16/2021,Second Class,California,Labels,2021,4,0.00,6.8714,2,14.6200
3,Furniture,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Tables,2020,7,0.45,-383.0310,5,957.5775
4,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,10/11/2020,US-2020-108966,33311.0,South,Consumer,10/18/2020,Standard Class,Florida,Storage,2020,7,0.20,2.5164,2,22.3680

In [23]:
store.head(3)

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Bookcases,2021,3,0.0,41.9136,2,261.96
1,Furniture,Henderson,United States,Claire Gute,11/8/2021,CA-2021-152156,42420.0,South,Consumer,11/11/2021,Second Class,Kentucky,Chairs,2021,3,0.0,219.5820,3,731.94
2,Office Supplies,Los Angeles,United States,Darrin Van Huff,6/12/2021,CA-2021-138688,90036.0,West,Corporate,6/16/2021,Second Class,California,Labels,2021,4,0.0,6.8714,2,14.62

In [24]:
store.tail()

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
9989,Technology,Los Angeles,United States,Ben Ferrer,12/24/2019,US-2019-138247,90045.0,West,Home Office,12/29/2019,Standard Class,California,Phones,2019,5,0.2,17.3656,7,173.656
9990,Technology,Los Angeles,United States,Ben Ferrer,7/12/2019,CA-2019-110184,90036.0,West,Home Office,7/16/2019,Standard Class,California,Phones,2019,4,0.2,28.7928,8,255.936
9991,Technology,Santa Barbara,United States,Maria Etezadi,6/6/2021,CA-2021-160717,93101.0,West,Home Office,6/11/2021,Standard Class,California,Phones,2021,5,0.2,226.7946,9,3023.928
9992,Technology,Yuma,United States,Gary Hansen,10/16/2022,CA-2022-159282,85364.0,West,Home Office,10/21/2022,Standard Class,Arizona,Machines,2022,5,0.7,-479.9880,5,599.985
9993,Technology,Louisville,United States,Sharelle Roach,4/17/2022,CA-2022-134845,80027.0,West,Home Office,4/23/2022,Standard Class,Colorado,Machines,2022,6,0.7,-3399.9800,5,2549.985

In [25]:
store.isna()

,Category,City,Country/Region,Customer Name,Order Date,Order ID,Postal Code,Region,Segment,Ship Date,Ship Mode,State,Sub-Category,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Introudce statistical concept in pandas ==>

In [26]:
store.describe()

,Postal Code,Year Label,Days to Ship,Discount,Profit,Quantity,Sales
count,9983.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,55245.233297,2020.722233,3.958475,0.156203,28.656896,3.789574,229.858001
std,32038.715955,1.123555,1.747603,0.206452,234.260108,2.225110,623.245101
min,1040.000000,2019.000000,0.000000,0.000000,-6599.978000,1.000000,0.444000
25%,23223.000000,2020.000000,3.000000,0.000000,1.728750,2.000000,17.280000
50%,57103.000000,2021.000000,4.000000,0.200000,8.666500,3.000000,54.490000
75%,90008.000000,2022.000000,5.000000,0.200000,29.364000,5.000000,209.940000
max,99301.000000,2022.000000,7.000000,0.800000,8399.976000,14.000000,22638.480000